--[[
	Roube um Brainrot (Steal a Brainrot) — Scanner de Plots + Webhook + Server Hop
	Requer executor com HTTP (syn.request / http.request) se HttpService estiver bloqueado no jogo.
]]

local Players = game:GetService("Players")
local TeleportService = game:GetService("TeleportService")
local HttpService = game:GetService("HttpService")

local LocalPlayer = Players.LocalPlayer

local WEBHOOK_URL =
	"https://discord.com/api/webhooks/1528792208864448664/cg6sguhE-Mf35TirgzhppvrOhRFe42-LaQxjUeAmD_G9Aq0_X42DDDeDLvDZQL2g0jIB"

local SCAN_WAIT_SECONDS = 10
local PLOTS_FOLDER_NAME = "Plots"

local OG_BRAINROTS = {
	"Skibidi Toilet",
	"Meowl",
	"Strawberry Elephant",
}

local SECRET_BRAINROTS = {
	"Hydra Dragon Cannelloni",
	"Headless Horseman",
	"Dragon Gingerini",
	"Dragon Cannelloni",
	"La Supreme Combinasion",
	"Cerberus",
	"Popcuru and Fizzuru",
	"Capitano Moby",
	"Cooki and Milki",
	"Burguro and Fryuro",
	"Ketupat Bros",
	"Reinito Sleighito",
	"La Secret Combinasion",
	"Fragrama and Chocrama",
	"La Casa Boo",
	"Spooky and Pumpky",
	"La Ginger Sekolah",
	"Ginger Gerat",
	"Los Spaghettis",
	"Festive 67",
	"Spaghetti Tualetti",
	"Garama and Madundung",
	"Lavadorito Spinito",
	"Jolly Jolly Sahur",
	"Ketchuru and Musturu",
	"Orcaledon",
	"Swaggy Bros",
	"Tictac Sahur",
	"Ketupat Kepat",
	"La Taco Combinasion",
	"Tang Tang Keletang",
	"Los Tacoritas",
	"Eviledon",
	"Los Primos",
	"W or L",
	"Esok Sekolah",
	"Los Puggies",
	"La Jolly Grande",
	"Tralaledon",
	"Gobblino Uniciclino",
	"Mieteteira Bicicleteira",
	"Tuff Toucan",
	"Money Money Reindeer",
	"Chipso and Queso",
	"Chillin Chili",
	"La Spooky Grande",
	"Bacuru and Egguru",
	"Los Bros",
	"La Extinct Grande",
	"Los Candies",
	"Los 67",
	"Celularcini Viciosini",
	"Los Mobilis",
	"Money Money Puggy",
	"Los Jolly Combinasionas",
	"Los Hotspositos",
	"Los Spooky Combinasionas",
	"Los Planitos",
	"Las Sis",
	"Spinny Hammy",
	"Tacorita Bicicleta",
	"Fishino Clownino",
	"Los Combinasionas",
	"Chicleteira Noelteira",
	"Nuclearo Dinossauro",
	"Chimnino",
	"Swag Soda",
	"Mariachi Corazoni",
	"La Grande Combinasion",
	"Los 25",
	"Los Burritos",
	"67",
	"Donkeyturbo Express",
	"Los Chicleteiras",
	"Guest 666",
	"Los Mi Gatitos",
	"Noo my Present",
	"Rang Ring Bus",
	"Los Nooo My Hotspotsitos",
	"Noo my Candy",
	"Arcadopus",
	"Los Quesadillas",
	"Chicleteirina Bicicleteirina",
	"Chill Puppy",
	"Burrito Bandito",
	"Quesadillo Vampiro",
	"Brunito Marsito",
	"Chicleteira Bicicleteira",
	"Ho Ho Ho Sahur",
	"Mi Gatito",
	"Naughty Naughty",
	"Bunito Bunito Spinito",
	"Quesadilla Crocodila",
	"Pot Pumpkin",
	"Horegini Boom",
	"Santa Hotspot",
	"Pirulitoita Bicicleteira",
	"25",
	"Pot Hotspot",
	"To to to Sahur",
	"List List List Sahur",
	"Telemorte",
	"La Sahur Combinasion",
	"Noo my examine",
	"Tung Tung Tung Sahur",
	"Bunnyman",
	"Los Jobcitos",
	"Nooo My Hotspot",
	"Cuadramat and Pakrahmatmamat",
	"Please my Present",
	"Los Cucarachas",
	"1x1x1x1",
	"Graipuss Medussi",
	"Perrito Burrito",
	"Giftini Spyderini",
	"GOAT",
	"Trickolino",
	"Triplito Tralaleritos",
	"La Vacca Jacko Linterino",
	"Santteo",
	"Los Karkeritos",
	"Las Vaquitas Saturnitas",
	"Karker Sahur",
	"Frankentteo",
	"Los Trios",
	"Job Job Job Sahur",
	"Las Tralaleritas",
	"Pumpkini Syderini",
	"Rocco Disco",
	"Extinct Matteo",
	"La Karkerkar Combinasion",
	"Reindeer Tralala",
	"La Vacca Prese Presente",
	"Yess my examine",
	"Guerriro Digitale",
	"Boatito Auratito",
	"Vulturino Skeletono",
	"Los Tralaleritos",
	"Los Tortus",
	"Zombie Tralala",
	"La Cucaracha",
	"Extinct Tralalero",
	"Fragola La La La",
	"Los Spyderinis",
	"Agarrini la Palini",
	"Chachechi",
	"Blackhole Goat",
	"Dul Dul Dul",
	"Torrtuginni Dragonfrutini",
	"Sammyni Spyderini",
	"Jackorilla",
	"Trenostruzzo Turbo 4000",
	"Karkerkar Kurkur",
	"Bisonte Giuppitere",
	"La Vacca Saturno Saturnita",
	"Los Matteos",
	"Chimpanzini Spiderini",
	"Tortuginni Dragonfruitini",
}
